- name: show shadow pass
  shell: cat /etc/shadow | grep "{{ user }}" | cut -f2 -d":"
  register: shadow_pass

- name: register shadow user line
  shell: cat /etc/shadow | grep "{{ user }}"
  register: full_shadow_pass

- name: copy shadow pass to file
  lineinfile:
    path: /etc/shadow.old
    line: "{{ full_shadow_pass.stdout }} {{ ansible_date_time.date }} {{ ansible_date_time.date }} {{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}:{{ ansible_date_time.second }}"
    state: present
    create: yes
  when: shadow_pass.stdout  not in lookup('file', '/etc/shadow.old')


- name: register random_pass
  shell: echo "{{ random_pass }}"
  register: random_pass_out

- name: write passwd in /root/root_pass_base.txt
  lineinfile:
    path: /root/root_pass_base.txt
    state: present
    line: "{{ random_pass_out.stdout }} {{ ansible_hostname }} {{ ansible_date_time.date }} {{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}:{{ ansible_date_time.second }}"
    create: yes
  delegate_to: localhost

- name: change pass
  user:
    name: "{{ user }}"
    password: "{{ random_pass_out.stdout | password_hash(salt=root_password_salt) }}"
    update_password: always
